name: Continuous integration

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.11.0
    - name: Build site
      run: devbox install && devbox run build
    - name: Upload site to bunny
      uses: ayeressian/bunnycdn-storage-deploy@v2.1.0
      with:
        source: "dist"
        storageZoneName: "${{ secrets.STORAGE_NAME }}"
        storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
        accessKey: "${{ secrets.BUNNY_API_KEY }}"
        pullZoneId: "${{ secrets.ZONE_ID }}"
        upload: "true"
        remove: "true"
        purgePullZone: "true"
